### ISSUE TITLE
Decentral-self-template must allow for user min/max vardiff. 

### ISSUE THREAD

**Issue by GTCLive** [OCEAN-xyz/datum_gateway#36]
There are no ways to unlock the strangely high pool min diff (set in the 130k), leaving low'er performing units to struggle and thus forcing this contributing group out. The Datum GW stratum works perfectly fine, however I would rebrand the concept and omit the 'decentralized-mind' marketing around the brand. 

Workaround is of course, let the mining community set their own desired min/max vardiff.

**Comment by luke-jr** [comment]
Share difficulty has no impact on how miners perform. Nor does it have any impact on decentralization.

**Comment by GTCLive** [comment]
Thanks. Not what was proposed though. In a decentral context it would make more a bit sense to leave the miners set their own difficulty, rather than being locked in the 100k  i.e. **let the mining community set their own desired min/max vardiff**. 

I'm guessing this pool high-diff preset is to weed out lower performing mining units? or is it simply to save bandwidth? What's with the high diff presets all over ocean.xyz? Just tried a few ports and some are as high as 260k (?!?!) 

Regardless of the reason. I'd still recommend a miner "self-set" vardiff as per OP, much like most other reputable pools around.

**Comment by GTCLive** [comment]
No worries, I'm currently mining on a fairly well established pool which enables auto difficulty adjustment (naturally). I still can't set my own diff, but at least the pool is smart enough to self/auto-adjust the difficulty based on the share rate. Fair. 

It's unfortunate that ocean.xyz is missing epically on that fundamental feature. Farewell then, I guess, and all the best of luck. 

I'll close this.

**Comment by BitcoinMechanic** [comment]
OCEAN does auto adjust based on share rate - target is 8 per minute.

**Comment by GTCLive** [comment]
> OCEAN does auto adjust based on share rate - target is 8 per minute.

Can you link up to the template please. I swear the last time I've tried OCEAN I was locked up in the mid 200k difficulty for half a day. Had to kill switch that nrg waste obviously...

I'd love to give it another try

**Comment by rkfg** [comment]
Does it actually go below 131072? How often does it auto adjust? I've just setup DATUM gateway and got this high diff too, for a Bitaxe that's quite a lot. Because the shares are solved every 8-10 minutes instead of "8 per minute" as you say the miner is shown as offline in the dashboard.

**Comment by BitcoinMechanic** [comment]
>if you're using an upstream pool you will be subjected to their minimum.

**Comment by rkfg** [comment]
Yes, I use OCEAN's upstream I suppose. I left the URL empty and it should default to `datum-beta1.mine.ocean.xyz`, since the server part is proprietary I think there's no point trying anything else. But you said: "OCEAN does auto adjust based on share rate - target is 8 per minute." — does that apply to DATUM as well? Or is 131072 the absolute minimum and it will never go below that?

**Comment by BitcoinMechanic** [comment]
Any other pool can support it, all we run as the upstream pool is just a local datum_gateway. The part that's "proprietary" is the reward split stuff which is TIDES related, nothing to do with DATUM.

OCEAN will just enforce a minimum that's all. If you aren't using it you can with with minimum difficulty whatever you want and tell it to auto-adjust for a target number of shares per minute.

**Comment by rkfg** [comment]
The weird part is that if I mine with `datafree.mine.ocean.xyz:3404` I get 16384 difficulty and it works well. But if I use DATUM I get 131072, why is that so? It looks counter-intuitive because I make the template and in theory the load on your servers should be much lower so why don't you allow more frequent shares with DATUM but do so with Stratum? Is there anything in the config I can set to get this lower diff? Currently my config looks like this (some ids redacted):
```json
{
    "bitcoind":{
        "rpcuser": "datum",
        "rpcpassword": "...",
        "rpcurl": "bitcoind:8332",
        "notify_fallback": false
    },
    "stratum": {
        "vardiff_min": 16384,
        "vardiff_target_shares_min": 1
    },
    "mining": {
        "pool_address": "bc1q...",
        "coinbase_tag_secondary": "my_tag",
        "coinbase_unique_id": 9182
    }
}
```
I suppose if I put any Stratum host in `datum.pool_host` it's not gonna work. Basically, as I see it now there are two options:
- mine with Stratum and get 2% fee
- mine with DATUM, get 1% fee but 8x diff which is inconvenient for a small miner such as Bitaxe (constantly shown as offline, shares are rare)

I fully support the point @GTCLive made, it doesn't look like a friendly attempt at mining decentralization and I absolutely don't see the reason for this kind of enforced settings. If there are too many shares per minute (in case of a big miner) the difficulty will auto adjust up anyway so there's no problem. Why punish small miners then?

**Comment by BitcoinMechanic** [comment]
It's temporary while we expand our back end. Yes it is inconvenient but it doesn't actually result in less earnings so it really shouldn't be too much of a concern.

**Comment by rkfg** [comment]
I'd argue it might result in less earnings if the hashrate is a drop in the Ocean (heh). If I understand it correctly, shares are weighted by their difficulty, so 8 shares mined at 16384 should pay the same amount that one share mined at 131072 does. It's never exactly the min diff but let's pretend it is for the sake of simplicity.

Now, when Ocean is big and mighty it might mine a couple of blocks in under 10 minutes. If I mine at 16384 I might squeeze in a few shares between those blocks. If I mine at 131072 the probability of hitting one share is much lower. Yeah, the difference would be just a few sats but it's there. Even 16384 is too much for your target rate of 8 shares/minute. In fact I get one share in 40-50 seconds so it should be 5 times lower.

Can you reopen this issue and maybe rename it? I'm interested in running DATUM but this variance doesn't look good, even the hashrate estimation goes down from 1.2 Th/s to 1.07 Th/s at 24h interval. Maybe it doesn't affect anything of course. Any ETA of that back end upgrade procedure? Will there be an announcement anywhere I can subscribe to?
